### ISSUE TITLE
support Cluster-API

### ISSUE THREAD

**Issue by helayoty** [kubernetes-sigs/e2e-framework#104]
support helper for cluster API

**Comment by vladimirvivien** [comment]
@helayoty 
Can you elaborate on how you would like to see Cluster-API supported ? Is it:
* Management cluster awareness
* Managed cluster awareness
* Ability to reach managed cluster automatically via management cluster
* Etc

**Comment by ShwethaKumbla** [comment]
@helayoty 
Is this helper func for custerctl like we have helper package for CRUD operations of k8s resources ?
If so I could explore [this](https://cluster-api.sigs.k8s.io/clusterctl/commands/commands.html) and come with initial draft PR.

**Comment by helayoty** [comment]
@vladimirvivien  & @ShwethaKumbla 

The idea for being able to support `Cluster API` is to spin up a `kind` cluster, install cluster API cli on it and then have a helper func for `clustercli`. Also, add a sample on how to use it with a couple of providers.

**Comment by johnSchnake** [comment]
I just created a duplicate issue. I think the main thing is that we just register the types so that you can use `klient` on those types as well. Currently you get a problem with the scheme not knowing about those types.

I'm working on implementing that now but the test cluster itself needs to have those types installed too. Going through that now we we can know it works as intended.

**Comment by johnSchnake** [comment]
I've got it nearly ready; I've gotten the types registered, clusterctl installed, etc. However, as I kept testing I hit https://github.com/kubernetes-sigs/cluster-api/issues/2450. I just found the issue just 1s ago and haven't had time to read it or implement the fix. PR probably tomorrow for this.

**Comment by vladimirvivien** [comment]
@helayoty can this be closed?
