### ISSUE TITLE
Constructor packages for building Kubernetes API workload objects

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/e2e-framework#114]
Constructing a graph for Kubernetes objects require tedious steps of specifying each entries in the graph. Often, this forces and requires the code writer to have to look up how to assemble the pieces so that the graph can be constructed properly.

For instance, the following code snippet shows how to programmatically create an object graph for a simple `Deployment`. As you can see, it takes many entries to create a complex object structure to satisfy the object graph for `Deployment`.

> Example pulled from [here](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/test/e2e/framework/deployment/fixtures.go?L41).

```go
func NewDeployment() *appV1.Deployment {
    return &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:   "my-deployment",
			Labels: podLabels,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{MatchLabels: podLabels},
			Strategy: appsv1.DeploymentStrategy{
				Type: appsV1.RecreateDeploymentStrategyType,
			},
			Template: v1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: podLabels,
				},
				Spec: v1.PodSpec{
					TerminationGracePeriodSeconds: &zero,
					Containers: []v1.Container{
						{
							Name:            containerName,
							Image:           image,
							SecurityContext: &v1.SecurityContext{},
						},
					},
				},
			},
		},
	}
}
```
As a test writer, it would be helpful and convenient if there exists an e2e-framework package that makes it easy to easily create objects without any knowledge of graph structure (as is required in the above example).  For instance, given a set of constructor packages, such as `constructor/deployment`, `constructor/pod`, `constructor/meta`, etc, the previous object graph could be created as follows:

```go

import (
    "sigs.k8s.io/e2e-framework/klient/constructors/deployment"
    "sigs.k8s.io/e2e-framework/klient/constructors/meta"
)

func NewDeployment() appsV1.Deployment {
    return deployment.Deployment(
        meta.Object("test-deployment").Namespace(meta.DefaultNamespace),
        deployment.Replicas(2),
        meta.MatchLabels(map[string]string{"server-type": "web"}),
        deployment.StrategyDefault,
        pod.Template(meta.ObjectMetaNone, pod.Spec(container.Name("server").Image("nginx").Commands("/start"))),
    )
}
```

**Comment by ficoos** [comment]
The examples you give are deceptive since you can write structs in a single line and span function calls across multiple lines.
The top example also specifies more information and is more flexible.
It's impossible to reduce the amount of information by moving to a "constructor" model since information density doesn't change.
You just get functions instead of structs. Function that has 5-10 parameters and the reader can't have any idea what any positional argument is. Or alternatively doing a function for each field which the same amount of chars as just specifying the field struct.

This problem can't be solved generically since you can't compress the information further.
What people usually do in tests is create builder for their common use cases which is also a struct.
```
deployment, statefulSet := FooTestResources{
   NamePrefix: "foo",
   Namespace: "default",
}.Build()
```
This works because in this specific context you know what parts don't need to be tuned or how the different fields relate to each other in your use case.

**Comment by vladimirvivien** [comment]
Thank you @ShwethaKumbla I still want to work on this (soon i hope).

**Comment by vladimirvivien** [comment]
Closing this for now until I can think of a better (code generated way) of doing this instead of manually.
