### ISSUE TITLE
[query] support for type `BenchmarkXxx`

### ISSUE THREAD

**Issue by diivm** [kubernetes-sigs/e2e-framework#133]
Does/will the framework support functions of the type `func BenchmarkXxx(*testing.B)`?

- For [benchmarks](https://pkg.go.dev/testing#hdr-Benchmarks), we have access to `*testing.B`, whereas the current test function `func (Environment).Test(*testing.T, ...Feature)` requires an argument of the type `*testing.T`

**Comment by vladimirvivien** [comment]
@divmadan this is interesting. I would love to hear more about your use case ? I think I understand what you are asking for, but could you show with some mock code? Thanks.

**Comment by divmadan** [comment]
@vladimirvivien I have been writing some table driven tests, and my requirement will be better suited to benchmarks as I don't need a pass/fail result.
Assuming a similar design as tests, they should look like:

<table>

<tr>
<td> 

**Test `go test . <flags>`**

</td>
<td>

**Benchmark `go test -bench=. <flags>`**

</td>
</tr>

<tr>
<td>

```go
func TestTable(t *testing.T) {
	testenv.Test(t, features.Table{
		{
			Name:       "Testcase1",
			Assessment: func(ctx context.Context, t *testing.T, config *envconf.Config) context.Context {
				// test assertions and fails
				return ctx
			},
		},
                {
			Name:       "Testcase2",
			Assessment: func(ctx context.Context, t *testing.T, config *envconf.Config) context.Context {
				// test assertions and fails
				return ctx
			},
		},
	}.
		Build("TestTable").
		WithLabel("mode", "random-mode").
		Setup(func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
			// setup
			return ctx
		}).
		Teardown(func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
			// teardown
                        return ctx
		}).
		Feature())
}
```

</td>
<td>

```go
func BenchmarkTable(b *testing.B) {
	testenv.Benchmark(b, features.Table{
		{
			Name:       "Benchmark1",
			Assessment: func(ctx context.Context, b *testing.B, config *envconf.Config) context.Context {
				// benchmark assertions and fails
				return ctx
			},
		},
                {
			Name:       "Benchmark2",
			Assessment: func(ctx context.Context, b *testing.B, config *envconf.Config) context.Context {
				// benchmark assertions and fails
				return ctx
			},
		},
	}.
		Build("BenchmarkTable").
		WithLabel("mode", "random-mode").
		Setup(func(ctx context.Context, b *testing.B, cfg *envconf.Config) context.Context {
			// setup
			return ctx
		}).
		Teardown(func(ctx context.Context, b *testing.B, cfg *envconf.Config) context.Context {
			// teardown
                        return ctx
		}).
		Feature())
}
```

</td>
</tr>

</table>

**Comment by vladimirvivien** [comment]
So @divmadan, what I think you are looking for is a way to express benchmark using the e2e-framework API. I put a sample below how this could work. 

```go
func  Benchmark_Hello(t *testing.B) {
	testenv := env.NewWithConfig(envconf.New())

	feat := features.NewBenchmark("Hello Feature").
		WithLabel("type", "simple benchmark").
		Setup(func(ctx context.Context, t *testing.B, _ *envconf.Config) context.Context {
			limit := 40000
                         return context.WithValue(ctx, "limit", 40000)
		}).
		Run("test message", func(ctx context.Context, b *testing.B, _ *envconf.Config) context.Context {
			limit := ctx.Value("limit").(int)
			for i := 0; i < b.N; i++ {
                             // do work to be bench marked
                             if i >= limit {
                                  b.Log("limit reached")
                             }
                         }
			return ctx
	       }).Feature()

	testenv.Benchmark(b, feat)
}
```

This example shows how this could work using the regular API.  Table support would also be added.

Thoughts?

**Comment by divm-dev** [comment]
This looks good @vladimirvivien. Since the framework wraps the `testing` module, we'll inherently support all benchmark capabilities similar to tests, right?

What is the scope of the changes required to implement this? I am under the assumption that a similar structure as tests' implementation would work, no specific logic for wrapping benchmarks will be required.

**Comment by divmadan** [comment]
This looks good @vladimirvivien. Since the framework wraps the `testing` module, we'll inherently support all benchmark capabilities similar to tests, right?

What is the scope of the changes required to implement this? I am under the assumption that a similar structure as tests' implementation would work, no specific logic for wrapping benchmarks will be required.

**Comment by harshanarayana** [comment]
```golang
type FeatureEnvFunc func(context.Context, *envconf.Config, *testing.T, Feature) (context.Context, error)
type TestEnvFunc func(context.Context, *envconf.Config, *testing.T) (context.Context, error)
```
There are types such as above that have already been defined. A good bit of these needs to be replicated for Benchmark specific case of we replace all `*testing.T` with `*testing.TB` interface and make that generic for both `*testing.T` and `*testing.B`. 

From whatever I could see from trying to write up a working prototype quickly, it turned out to be a lot more changes that I thought.

**Comment by divmadan** [comment]
Can I help with the implementation?

**Comment by vladimirvivien** [comment]
@harshanarayana Honestly, I didn't even go look in Go's test API to see if this (wrapping and running benchmarks) can be done. As it turns out, type `testing.B` has method `func (b *B) Run(name string, f func(b *B)) bool` (similar to `testing.T`) which can be used to launch benchmarks programmatically.

Nevertheless, if this is to be done, it would require additional API entry points instead of reusing existing ones. For instance, instead of `FeatureEnvFunc`, maybe a new type is introduced specifically for handling benchmarks `FeatureBenchmarkEnvFunc` as an example.

Furthermore, before any code is written. We should really debate whether this is something that would be useful to the community.  It sounds like it would be, but I would like to hear from others and also, are there instances in Kubernetes testing where Benchmarks are used ?

**Comment by harshanarayana** [comment]
@vladimirvivien I agree with you.. May be we start with a simple design proposal.. Document few approaches we have and we see if they are required or can be done in a different way?

**Comment by vladimirvivien** [comment]
If this is not of interest to anyone else, we probably should just let it go stale (cc @harshanarayana )
