### ISSUE TITLE
Gracefully exit when setup fail

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes-sigs/e2e-framework#188]
https://github.com/kubernetes-sigs/e2e-framework/blob/d19e8b569fb2f94568f8ed74b00227f879798aa0/pkg/env/env.go#L369

Due to the usage of `klog.Fatalf()`, it calls internally `os.Exit()`, and we can't gracefully run the clean ups.

**Comment by vladimirvivien** [comment]
@AlmogBaku thank you for pointing this out. Can you provide a bit more information or context so that an appropriate fix may be implemented.

**Comment by harshanarayana** [comment]
@AlmogBaku if the workflow were to fail during the setup, don't you want to retain the setup intact instead of cleaning up ? This might help in digging into what actually caused the setup to fails easily right ?

There is an option similar to this called `disable-graceful-teardown` that we enabled a while ago that can prevent teardown on the test failure. Are you suggesting for an option similar to that but the one that can handle setup failures ?

**Comment by vladimirvivien** [comment]
@harshanarayana I went ahead and label this as a bug. The internal logger should not disrupt the execution flow of the users test.

**Comment by codegold79** [comment]
I'd like to work on this issue. I'll try to reproduce the problem of panic after failed set up as my first step.
