### ISSUE TITLE
panic handler hides source of panic

### ISSUE THREAD

**Issue by chlunde** [kubernetes-sigs/e2e-framework#289]
If there is a panic in a env.Setup EnvFunc, the source line is logged as env.go. Printing the stack trace or top frame would be helpful.

https://github.com/kubernetes-sigs/e2e-framework/blob/15e91144243aab9c611f5706c3e7c48ceb881850/pkg/env/env.go#L345-L354

Result on panic:
```
E0626 23:32:53.995230   25448 env.go:353] Recovering from panic and running finish actionsreflect: call of reflect.Value.Type on zero Value
```

**Comment by harshanarayana** [comment]
I think it would be nice to dump the entire stack itself. 

`klog.ErrorS(e, "Recovering from panic and running finish actions", "stack", string(debug.Stack()))`

I believe something like this could be done. I noticed the formatting of the string was a bit off too because of how we were using `klog.Error` instead of `klog.Errorf` or `klog.ErrorS`

@chlunde  Would you be interested in opening a PR for this ?
