### ISSUE TITLE
Feature Builder doesn't support adding Step by name

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes-sigs/e2e-framework#94]
The `feature` builder has a nice set of API exposed to be able to build setup and tear down methods.  But they auto generate the name of the step that is being run.

```go
fmt.Sprintf("%s-setup", b.feat.name)
```
However, this can be a bit of a problem to debug things. There is a really useful builder method called `WithStep` that can let you customize the name of the step. However, the argument used `level` used for this is coming from `pkg/internal/types/level.go`

```go
// WithStep adds a new step that will be applied prior to feature test.
func (b *FeatureBuilder) WithStep(name string, level Level, fn Func) *FeatureBuilder {
	b.feat.steps = append(b.feat.steps, newStep(name, level, fn))
	return b
}
```

Which means we can't really use that or invoke it from anywhere outside. Which means the examples can't use that either or anything that injects `e2e-framework` as a dependency. Does it make sense to move some bits from `pkg/internal/types` to a reusable package ?

**Comment by vladimirvivien** [comment]
@harshanarayana Thanks for bringing that up.

Right now the api supports very specific sets of steps
* Assessment
* Setup
* Teardown
* (might be one more)

Some of the pre-baked steps above do have auto-generate names (except Assessment).  This is because the internal method `FeatureBuilder.WithStep` requires a name.  The reason `WithStep` is hidden is because each step type, specified by Level (i.e. Assess, Setup, Teardown, etc) are treated differently during execution.

Maybe, one thing that can be done is to extend the Feature API to allow Setup and Teardown to have names as well as shown below:

```go
func TestHello_WithSetup(t *testing.T) {
	e := env.NewWithConfig(envconf.New())
	var name string
	feat := features.New("Hello Feature").
		WithLabel("type", "simple").
		WithSetup("SetupName", func(ctx context.Context, t *testing.T, _ *envconf.Config) context.Context {
			name = "foobar"
			return ctx
		}).
		Assess("test message", func(ctx context.Context, t *testing.T, _ *envconf.Config) context.Context {
			result := Hello(name)
			if result != "Hello foobar" {
				t.Error("unexpected message")
			}
			return ctx
		}).WithTeardown("Teardown", func(ctx context.Context, t *testing.T, _ *envconf.Config) context.Context {
                ...
		}).Feature()

	e.Test(t, feat)
}
```

**Comment by harshanarayana** [comment]
@vladimirvivien  I see what you mean. 
I do like the idea of extending the feature API to provide additional option to be able to provide step names. Makes it a bit more readable and easy to debug. Let me have a Draft PR opened on this for review.
